---
# Synopsis
# This playbook manages the observe-agent service on all target hosts by stopping the service, updating configuration files, restarting the service, and validating its status.

# Description
# The playbook performs the following tasks:
# 1. Stops the observe-agent service to safely apply configuration changes.
# 2. Copies the custom otel-collector configuration file to the specified directory on the target host.
# 3. Copies the custom logs configuration file to the specified directory on the target host.
# 4. Restarts the observe-agent service to apply the new configurations.
# 5. Ensures the observe-agent service is running and enabled to start at boot.

# Notes
# - Verify that configuration file paths are correct and accessible.
# - Ensure the observe-agent service is installed and configured correctly on all target hosts.
# - Adjust file permissions and ownership as needed to match your environment.

# Example
# To run this playbook, execute:
# ansible-playbook -i <inventory_file> <playbook.yml> --limit <hostname_or_group>
#
# Replace `<inventory_file>` with the path to your inventory file and `<playbook.yml>` with the name of this playbook.

- name: Update Observe configuration
  hosts: all
  become: true

  tasks:
  # Stop the observe-agent service to safely apply configuration changes.
  - name: Stop Observe Agent Service
    service:
      name: observe-agent
      state: stopped
    changed_when: True
    notify:
      - Restart Observe Agent Service

  # Gather facts about the target host.
  - name: Gather facts
    setup:
    changed_when: True

  # Copy the custom otel-collector configuration file for Ubuntu 24.04.
  - name: Copy custom otel-collector.yaml for Ubuntu 24.04
    copy:
      src: "{{ role_path }}/files/observe/{{ os_version }}-otel-collector.yaml"
      dest: /etc/observe-agent/otel-collector.yaml
      owner: root
      group: root
      mode: '0644'
    when:
      - ansible_os_family == 'Debian'
      - os_version == '24.04'
    changed_when: True
    notify:
      - Restart Observe Agent Service

  # Copy the custom logs configuration file for Ubuntu 24.04.
  - name: Copy custom logs.yaml for Ubuntu 24.04
    copy:
      src: "{{ role_path }}/files/observe/{{ os_version }}-logs.yaml"
      dest: /etc/observe-agent/connections/host_monitoring/logs.yaml
      owner: root
      group: root
      mode: '0644'
    when:
      - ansible_os_family == 'Debian'
      - os_version == '24.04'
    changed_when: True
    notify:
      - Restart Observe Agent Service

  # Copy the default otel-collector configuration file for other OS versions.
  - name: Copy default otel-collector.yaml for other OS versions
    copy:
      src: "{{ role_path }}/files/observe/otel-collector.yaml"
      dest: /etc/observe-agent/otel-collector.yaml
      owner: root
      group: root
      mode: '0644'
    when:
      - ansible_os_family == 'Debian'
      - os_version != '24.04'
    changed_when: True
    notify:
      - Restart Observe Agent Service

  # Copy the default logs configuration file for other OS versions.
  - name: Copy default logs.yaml for other OS versions
    copy:
      src: "{{ role_path }}/files/observe/logs.yaml"
      dest: /etc/observe-agent/connections/host_monitoring/logs.yaml
      owner: root
      group: root
      mode: '0644'
    when:
      - ansible_os_family == 'Debian'
      - os_version != '24.04'
    changed_when: True
    notify:
      - Restart Observe Agent Service

  # Restart the observe-agent service to apply the new configurations.
  - name: Restart Observe Agent Service
    service:
      name: observe-agent
      state: restarted
    changed_when: True

  # Ensure the observe-agent service is running and enabled to start at boot.
  - name: Ensure observe-agent service is running and enabled
    ansible.builtin.systemd:
      name: observe-agent
      state: started
      enabled: yes
    changed_when: True

